### ISSUE TITLE
这个是什么原因！

### ISSUE THREAD

**Issue by gkjolin** [anlingbbq/MOBAGame#1]
System.IO.FileLoadException: 未能加载文件或程序集“ExitGamesLibs, Version=1.0.1.0, Culture=neutral, PublicKeyToken=eac0edd9746a4aa0”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
文件名:“ExitGamesLibs, Version=1.0.1.0, Culture=neutral, PublicKeyToken=eac0edd9746a4aa0”
   在 MOBAServer.MobaServer.InitLog()
   在 MOBAServer.MobaServer.Setup() 位置 C:\Users\Administrator\Downloads\MOBAGame-master\MOBAServer\MOBAServer\MobaServer.cs:行号 43
   在 Photon.SocketServer.ApplicationBase.PhotonHostRuntimeInterfaces.IPhotonControl.OnPhotonRunning()
   在 PhotonHostRuntime.PhotonDomainManager.PhotonPlainAppDomainBehavior.PhotonRunning()
   在 PhotonHostRuntime.PhotonDomainManager.PhotonRunning()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

**Comment by anlingbbq** [comment]
你好，我不清楚这个问题的具体原因，建议你找下PhotonServer的配置教程，系统学习下

在 2017-12-18 16:04:44，"SpaceG" <notifications@github.com> 写道：


System.IO.FileLoadException: 未能加载文件或程序集“ExitGamesLibs, Version=1.0.1.0, Culture=neutral, PublicKeyToken=eac0edd9746a4aa0”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
文件名:“ExitGamesLibs, Version=1.0.1.0, Culture=neutral, PublicKeyToken=eac0edd9746a4aa0”
在 MOBAServer.MobaServer.InitLog()
在 MOBAServer.MobaServer.Setup() 位置 C:\Users\Administrator\Downloads\MOBAGame-master\MOBAServer\MOBAServer\MobaServer.cs:行号 43
在 Photon.SocketServer.ApplicationBase.PhotonHostRuntimeInterfaces.IPhotonControl.OnPhotonRunning()
在 PhotonHostRuntime.PhotonDomainManager.PhotonPlainAppDomainBehavior.PhotonRunning()
在 PhotonHostRuntime.PhotonDomainManager.PhotonRunning()

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。
